### 3.2 Data Preparation

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('Telco-Customer-Churn.csv')
df.head()
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [2]:
df.gender.value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [3]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
str_cols = df.dtypes[df.dtypes == 'object'].index
for col in str_cols:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [4]:
df.isnull().sum()

customerid           0
gender               0
seniorcitizen        0
partner              0
dependents           0
tenure               0
phoneservice         0
multiplelines        0
internetservice      0
onlinesecurity       0
onlinebackup         0
deviceprotection     0
techsupport          0
streamingtv          0
streamingmovies      0
contract             0
paperlessbilling     0
paymentmethod        0
monthlycharges       0
totalcharges        11
churn                0
dtype: int64

In [5]:
for col in df.columns:
    print(f'***{col}***')
    print('Unique: ', df[col].nunique())
    print(df[col].value_counts())
    print('data type:' , df[col].dtype)
    print()

***customerid***
Unique:  7043
customerid
3186-ajiek    1
7590-vhveg    1
5575-gnvde    1
8775-cebbj    1
2823-lkabh    1
             ..
6713-okomc    1
1452-kiovk    1
9305-cdskc    1
9237-hqitu    1
7795-cfocw    1
Name: count, Length: 7043, dtype: int64
data type: object

***gender***
Unique:  2
gender
male      3555
female    3488
Name: count, dtype: int64
data type: object

***seniorcitizen***
Unique:  2
seniorcitizen
0    5901
1    1142
Name: count, dtype: int64
data type: int64

***partner***
Unique:  2
partner
no     3641
yes    3402
Name: count, dtype: int64
data type: object

***dependents***
Unique:  2
dependents
no     4933
yes    2110
Name: count, dtype: int64
data type: object

***tenure***
Unique:  73
tenure
1     613
72    362
2     238
3     200
4     176
     ... 
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64
data type: int64

***phoneservice***
Unique:  2
phoneservice
yes    6361
no      682
Name: count, dtype: int64
data ty

In [6]:
df.totalcharges = df.totalcharges.fillna(0)

In [7]:
df.totalcharges.isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
7038    False
7039    False
7040    False
7041    False
7042    False
Name: totalcharges, Length: 7043, dtype: bool

In [8]:
df.churn = (df.churn == 'yes').astype(int)
df.head()

customerid  gender  seniorcitizen partner dependents  tenure phoneservice  \
0  7590-vhveg  female              0     yes         no       1           no   
1  5575-gnvde    male              0      no         no      34          yes   
2  3668-qpybk    male              0      no         no       2          yes   
3  7795-cfocw    male              0      no         no      45           no   
4  9237-hqitu  female              0      no         no       2          yes   

      multiplelines internetservice onlinesecurity  ... deviceprotection  \
0  no_phone_service             dsl             no  ...               no   
1                no             dsl            yes  ...              yes   
2                no             dsl            yes  ...               no   
3  no_phone_service             dsl            yes  ...              yes   
4                no     fiber_optic             no  ...               no   

  techsupport streamingtv streamingmovies        contract paperlessbilling  \
0          no          no              no  month-to-month              yes   
1          no          no              no        one_year               no   
2          no          no              no  month-to-month              yes   
3         yes          no              no        one_year               no   
4          no          no              no  month-to-month              yes   

               paymentmethod monthlycharges  totalcharges  churn  
0           electronic_check          29.85         29.85      0  
1               mailed_check          56.95       1889.50      0  
2               mailed_check          53.85        108.15      1  
3  bank_transfer_(automatic)          42.30       1840.75      0  
4           electronic_check          70.70        151.65      1  

[5 rows x 21 columns]

### validation framework using scikit learn

In [9]:
from sklearn.model_selection import train_test_split
df_fulltrain, df_test = train_test_split(df,test_size=0.2,random_state=1)
df_train, df_val = train_test_split(df_fulltrain, test_size=0.25, random_state=1)

In [10]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [11]:
y_train = df_train.churn
y_val = df_val.churn
y_test = df_val.churn

del df_train['churn']
del df_val['churn']
del df_test['churn']

del df_train['customerid']
del df_val['customerid']
del df_test['customerid']


### Exploratory Data Analysis EDA

In [12]:
df_fulltrain = df_fulltrain.reset_index(drop=True)
numerical = ['tenure','totalcharges','monthlycharges']
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']
fields = numerical + categorical
fields

['tenure',
 'totalcharges',
 'monthlycharges',
 'gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

In [13]:
df_fulltrain.churn.value_counts(normalize=True)
global_churn_rate = round(df_fulltrain.churn.mean(), 2)
global_churn_rate

np.float64(0.27)

### Feature Importance - Churn rate and risk ratio

In [14]:
df_fulltrain[df_fulltrain.gender == 'male'].churn.mean()

np.float64(0.2632135306553911)

In [15]:
from IPython.display import display

for col in categorical:
    tr = df_fulltrain.groupby(col).churn.agg(['mean'])
    tr['diff'] = (global_churn_rate - tr['mean']).round(2)
    tr['risk'] = (tr['mean']/global_churn_rate).round(2)
    display(tr)

mean  diff  risk
gender                      
female  0.276824 -0.01  1.03
male    0.263214  0.01  0.97

mean  diff  risk
seniorcitizen                      
0              0.242270  0.03  0.90
1              0.413377 -0.14  1.53

mean  diff  risk
partner                      
no       0.329809 -0.06  1.22
yes      0.205033  0.06  0.76

mean  diff  risk
dependents                      
no          0.313760 -0.04  1.16
yes         0.165666  0.10  0.61

mean  diff  risk
phoneservice                      
no            0.241316  0.03  0.89
yes           0.273049 -0.00  1.01

mean  diff  risk
multiplelines                         
no                0.257407  0.01  0.95
no_phone_service  0.241316  0.03  0.89
yes               0.290742 -0.02  1.08

mean  diff  risk
internetservice                      
dsl              0.192347  0.08  0.71
fiber_optic      0.425171 -0.16  1.57
no               0.077805  0.19  0.29

mean  diff  risk
onlinesecurity                           
no                   0.420921 -0.15  1.56
no_internet_service  0.077805  0.19  0.29
yes                  0.153226  0.12  0.57

mean  diff  risk
onlinebackup                             
no                   0.404323 -0.13  1.50
no_internet_service  0.077805  0.19  0.29
yes                  0.217232  0.05  0.80

mean  diff  risk
deviceprotection                         
no                   0.395875 -0.13  1.47
no_internet_service  0.077805  0.19  0.29
yes                  0.230412  0.04  0.85

mean  diff  risk
techsupport                              
no                   0.418914 -0.15  1.55
no_internet_service  0.077805  0.19  0.29
yes                  0.159926  0.11  0.59

mean  diff  risk
streamingtv                              
no                   0.342832 -0.07  1.27
no_internet_service  0.077805  0.19  0.29
yes                  0.302723 -0.03  1.12

mean  diff  risk
streamingmovies                          
no                   0.338906 -0.07  1.26
no_internet_service  0.077805  0.19  0.29
yes                  0.307273 -0.04  1.14

mean  diff  risk
contract                            
month-to-month  0.431701 -0.16  1.60
one_year        0.120573  0.15  0.45
two_year        0.028274  0.24  0.10

mean  diff  risk
paperlessbilling                      
no                0.172071  0.10  0.64
yes               0.338151 -0.07  1.25

mean  diff  risk
paymentmethod                                  
bank_transfer_(automatic)  0.168171  0.10  0.62
credit_card_(automatic)    0.164339  0.11  0.61
electronic_check           0.455890 -0.19  1.69
mailed_check               0.193870  0.08  0.72

### Feature Importance Mutual Information

In [16]:
from sklearn.metrics import mutual_info_score
def mutual_information_score(series):
    return mutual_info_score(series, df_fulltrain.churn)
df_fulltrain[categorical].apply(mutual_information_score).sort_values(ascending=False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

### Feature Importance - Correlation for numerical variables

In [17]:
df_fulltrain[numerical].corrwith(df_fulltrain.churn).abs()

tenure            0.351885
totalcharges      0.196353
monthlycharges    0.196805
dtype: float64

In [18]:
df_fulltrain[df_fulltrain.tenure < 20].churn.mean()

np.float64(0.4437555358724535)

In [19]:
df_fulltrain[(df_fulltrain.tenure > 20) & (df_fulltrain.tenure < 50)].churn.mean()

np.float64(0.21598002496878901)

In [20]:
df_fulltrain[df_fulltrain.tenure > 50].churn.mean()

np.float64(0.09025270758122744)

## feature extraction - one hot encoding 

In [21]:
dicts = df_fulltrain[:10][['gender','contract','onlinesecurity']].to_dict(orient='records')
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
dv.fit(dicts)
dv.transform(dicts)


array([[0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0.]])

In [22]:
dict_train = df_train.to_dict(orient = 'records')
dv.fit(dict_train)
X_train = dv.transform(dict_train)
dict_val = df_val.to_dict(orient = 'records')
X_val = dv.transform(dict_val)

### Training Logistic regression with Scikit Learn

In [23]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 10000000000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000000000)

In [24]:
w = model.coef_[0]
w0 = model.intercept_[0]
w0

np.float64(-0.045323382519725265)

In [25]:
predict = model.predict(X_val)
predict

array([0, 0, 0, ..., 0, 1, 1], shape=(1409,))

In [26]:
probability = model.predict_proba(X_val)[:,1].round(2)
probability

array([0.01, 0.2 , 0.22, ..., 0.15, 0.79, 0.81], shape=(1409,))

In [27]:
result = pd.DataFrame()
result['probability'] = probability
result['predict'] = predict
result['actual'] = y_val
result['correct'] = result['predict'] == y_val
result

probability  predict  actual  correct
0            0.01        0       0     True
1            0.20        0       0     True
2            0.22        0       0     True
3            0.56        1       1     True
4            0.22        0       0     True
...           ...      ...     ...      ...
1404         0.29        0       0     True
1405         0.04        0       1    False
1406         0.15        0       0     True
1407         0.79        1       1     True
1408         0.81        1       1     True

[1409 rows x 4 columns]

In [28]:
accuracy = result.correct.mean()
accuracy

np.float64(0.8034066713981547)

In [38]:
dv = DictVectorizer(sparse=False)
df_fulltrain = df_fulltrain.reset_index(drop=True)
dict_fulltrain = df_fulltrain[fields].to_dict(orient="records")
dv.fit(dict_fulltrain)
X_fulltrain = dv.transform(dict_fulltrain)
y_fulltrain = df_fulltrain.churn.values
model.fit(np.concatenate([X_train, X_val]), np.concatenate([y_train, y_val]))
w = model.coef_[0]
w0 = model.intercept_[0]
w0

np.float64(-0.12307907358470903)

In [39]:
dict_test = df_test[fields].to_dict(orient='records')
X_test = dv.transform(dict_test)
probability = model.predict_proba(X_test)[:,1].round(2)
churn_decision = (probability > 0.5)
(churn_decision == y_test).mean()

np.float64(0.6188786373314408)